
package wsdlfirstcode;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2017-02-07T15:12:06.454+05:30
 * Generated source version: 2.5.1
 * 
 */
public final class HelloWorldService_HelloWorldServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://helloworld/", "HelloWorldServiceImplService");

    private HelloWorldService_HelloWorldServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HelloWorldServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HelloWorldServiceImplService ss = new HelloWorldServiceImplService(wsdlURL, SERVICE_NAME);
        HelloWorldService port = ss.getHelloWorldServiceImplPort();  
        
        {
        System.out.println("Invoking print...");
        java.lang.String _print_arg0 = "";
        java.lang.String _print__return = port.print(_print_arg0);
        System.out.println("print.result=" + _print__return);


        }
        {
        System.out.println("Invoking getAccount...");
        wsdlfirstcode.AccountInfo _getAccount__return = port.getAccount();
        System.out.println("getAccount.result=" + _getAccount__return);


        }

        System.exit(0);
    }

}
