package wsdlfirstcode;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2017-02-07T15:12:06.513+05:30
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://helloworld/", name = "HelloWorldService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorldService {

    @WebMethod
    @RequestWrapper(localName = "print", targetNamespace = "http://helloworld/", className = "wsdlfirstcode.Print")
    @ResponseWrapper(localName = "printResponse", targetNamespace = "http://helloworld/", className = "wsdlfirstcode.PrintResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String print(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://helloworld/", className = "wsdlfirstcode.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://helloworld/", className = "wsdlfirstcode.GetAccountResponse")
    @WebResult(name = "return", targetNamespace = "")
    public wsdlfirstcode.AccountInfo getAccount();
}
